# Generated by Django 5.0.1 on 2024-01-23 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "published",
                    models.BooleanField(default=True, verbose_name="Опубликовано"),
                ),
                ("title", models.CharField(verbose_name="Заголовок")),
                (
                    "background",
                    models.ImageField(upload_to="", verbose_name="Картинка"),
                ),
                ("link", models.CharField(blank=True, verbose_name="Ссылка")),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
            },
        ),
        migrations.CreateModel(
            name="Social",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "published",
                    models.BooleanField(default=True, verbose_name="Опубликовано"),
                ),
                ("title", models.CharField(verbose_name="Закголовок")),
                ("icon", models.ImageField(upload_to="", verbose_name="Иконка")),
                ("link", models.CharField(verbose_name="Ссылка")),
            ],
            options={
                "verbose_name": "Соцсеть",
                "verbose_name_plural": "Социальные сети",
            },
        ),
        migrations.CreateModel(
            name="Update",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "published",
                    models.BooleanField(default=True, verbose_name="Опубликовано"),
                ),
                ("version", models.CharField(verbose_name="Версия")),
                (
                    "beta",
                    models.BooleanField(
                        default=False, verbose_name="Для бета-тестеров"
                    ),
                ),
                (
                    "clean_profiles",
                    models.BooleanField(default=False, verbose_name="Удалить профили"),
                ),
                (
                    "clean_inis",
                    models.BooleanField(
                        default=True,
                        help_text="Modorganizer.ini, nemesis.ini",
                        verbose_name="Удалить .ini файлы",
                    ),
                ),
                (
                    "update_file",
                    models.FileField(
                        help_text="Архив или торрент",
                        upload_to="",
                        verbose_name="Файл обновления",
                    ),
                ),
                (
                    "mods_to_remove",
                    models.TextField(
                        blank=True,
                        help_text="Список папок без кавычек и прочей хуйни, через запятую",
                        verbose_name="Моды на удаление",
                    ),
                ),
                (
                    "files_to_remove",
                    models.TextField(
                        blank=True,
                        help_text="Если нужно удалить конкретные файлы, правила те же, путь от FlappyRU. Например: mods/мод_на_еблю_с_рыбами/карась.ini, ModOrganiser.ini",
                        verbose_name="Файлы на удаление",
                    ),
                ),
                (
                    "previous",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_main.update",
                    ),
                ),
            ],
            options={
                "verbose_name": "Обновление",
                "verbose_name_plural": "Обновления",
            },
        ),
    ]
