# Generated by Django 5.0.1 on 2024-01-23 04:35

import django.db.models.deletion
from django.db import migrations, models


def create_default(apps, schema_editor):
    Update = apps.get_model("app_main", "Update")
    Update.objects.create(version="2.4.0")
    Update.objects.create(version="2.4.0", lang="EN")


class Migration(migrations.Migration):
    dependencies = [
        ("app_main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="update",
            name="previous",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app_main.update",
                verbose_name="Обновление с",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="update_file",
            field=models.FileField(
                help_text="Архив или торрент",
                null=True,
                upload_to="",
                verbose_name="Файл обновления",
            ),
        ),
        migrations.RunPython(create_default),
    ]
