version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server_flappy
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    restart: always
    environment:
      DJANGO_SETTINGS_MODULE: "settings.local"
    ports:
      - 8000:8000
    volumes:
      - ./server:/home/python/app

  db:
    image: postgres:16-alpine
    container_name: db_flappy
    ports:
      - 5432:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      PSQL_PASSWORD: "12345"
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: "flappy"
      POSTGRES_DB: "flappy"
